// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/dmutex.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DMutexService_DistribuedMutexService_FullMethodName = "/DMutexService/DistribuedMutexService"
)

// DMutexServiceClient is the client API for DMutexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DMutexServiceClient interface {
	DistribuedMutexService(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type dMutexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDMutexServiceClient(cc grpc.ClientConnInterface) DMutexServiceClient {
	return &dMutexServiceClient{cc}
}

func (c *dMutexServiceClient) DistribuedMutexService(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resp)
	err := c.cc.Invoke(ctx, DMutexService_DistribuedMutexService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMutexServiceServer is the server API for DMutexService service.
// All implementations must embed UnimplementedDMutexServiceServer
// for forward compatibility.
type DMutexServiceServer interface {
	DistribuedMutexService(context.Context, *Req) (*Resp, error)
	mustEmbedUnimplementedDMutexServiceServer()
}

// UnimplementedDMutexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDMutexServiceServer struct{}

func (UnimplementedDMutexServiceServer) DistribuedMutexService(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistribuedMutexService not implemented")
}
func (UnimplementedDMutexServiceServer) mustEmbedUnimplementedDMutexServiceServer() {}
func (UnimplementedDMutexServiceServer) testEmbeddedByValue()                       {}

// UnsafeDMutexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DMutexServiceServer will
// result in compilation errors.
type UnsafeDMutexServiceServer interface {
	mustEmbedUnimplementedDMutexServiceServer()
}

func RegisterDMutexServiceServer(s grpc.ServiceRegistrar, srv DMutexServiceServer) {
	// If the following call pancis, it indicates UnimplementedDMutexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DMutexService_ServiceDesc, srv)
}

func _DMutexService_DistribuedMutexService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMutexServiceServer).DistribuedMutexService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DMutexService_DistribuedMutexService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMutexServiceServer).DistribuedMutexService(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// DMutexService_ServiceDesc is the grpc.ServiceDesc for DMutexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DMutexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DMutexService",
	HandlerType: (*DMutexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistribuedMutexService",
			Handler:    _DMutexService_DistribuedMutexService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dmutex.proto",
}
