// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/Dmutex.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DmutexService_Dmutex_FullMethodName = "/DmutexService/Dmutex"
)

// DmutexServiceClient is the client API for DmutexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DmutexServiceClient interface {
	Dmutex(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Req, Ack], error)
}

type dmutexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDmutexServiceClient(cc grpc.ClientConnInterface) DmutexServiceClient {
	return &dmutexServiceClient{cc}
}

func (c *dmutexServiceClient) Dmutex(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Req, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DmutexService_ServiceDesc.Streams[0], DmutexService_Dmutex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Req, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DmutexService_DmutexClient = grpc.BidiStreamingClient[Req, Ack]

// DmutexServiceServer is the server API for DmutexService service.
// All implementations must embed UnimplementedDmutexServiceServer
// for forward compatibility.
type DmutexServiceServer interface {
	Dmutex(grpc.BidiStreamingServer[Req, Ack]) error
	mustEmbedUnimplementedDmutexServiceServer()
}

// UnimplementedDmutexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDmutexServiceServer struct{}

func (UnimplementedDmutexServiceServer) Dmutex(grpc.BidiStreamingServer[Req, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method Dmutex not implemented")
}
func (UnimplementedDmutexServiceServer) mustEmbedUnimplementedDmutexServiceServer() {}
func (UnimplementedDmutexServiceServer) testEmbeddedByValue()                       {}

// UnsafeDmutexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DmutexServiceServer will
// result in compilation errors.
type UnsafeDmutexServiceServer interface {
	mustEmbedUnimplementedDmutexServiceServer()
}

func RegisterDmutexServiceServer(s grpc.ServiceRegistrar, srv DmutexServiceServer) {
	// If the following call pancis, it indicates UnimplementedDmutexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DmutexService_ServiceDesc, srv)
}

func _DmutexService_Dmutex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DmutexServiceServer).Dmutex(&grpc.GenericServerStream[Req, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DmutexService_DmutexServer = grpc.BidiStreamingServer[Req, Ack]

// DmutexService_ServiceDesc is the grpc.ServiceDesc for DmutexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DmutexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DmutexService",
	HandlerType: (*DmutexServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dmutex",
			Handler:       _DmutexService_Dmutex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/Dmutex.proto",
}
